version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-network

  # User Service
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://todouser:todopass@postgres:5432/tododb
      JWT_SECRET: your-super-secret-jwt-key-here
      PORT: 3001
    depends_on:
      - postgres
    networks:
      - todo-network
    # volumes:
    #   - ./user-service:/app
    #   - /app/node_modules

  # Todo Service
  todo-service:
    build: ./todo-service
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://todouser:todopass@postgres:5432/tododb
      JWT_SECRET: your-super-secret-jwt-key-here
      PORT: 3002
    depends_on:
      - postgres
    networks:
      - todo-network
    # volumes:
    #   - ./todo-service:/app
    #   - /app/node_modules

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      USER_SERVICE_URL: http://user-service:3001
      TODO_SERVICE_URL: http://todo-service:3002
    depends_on:
      - user-service
      - todo-service
    networks:
      - todo-network

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge