version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tododb_test
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser -d tododb_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service-test:
    build:
      context: ./user-service
      dockerfile: Dockerfile.test
    environment:
      DATABASE_URL: postgresql://todouser:todopass@postgres-test:5432/tododb_test
      TEST_DATABASE_URL: postgresql://todouser:todopass@postgres-test:5432/tododb_test
      JWT_SECRET: test-secret-key
    depends_on:
      postgres-test:
        condition: service_healthy
    volumes:
      - ./user-service:/app
      - /app/node_modules

  todo-service-test:
    build:
      context: ./todo-service
      dockerfile: Dockerfile.test
    environment:
      DATABASE_URL: postgresql://todouser:todopass@postgres-test:5432/tododb_test
      TEST_DATABASE_URL: postgresql://todouser:todopass@postgres-test:5432/tododb_test
      JWT_SECRET: test-secret-key
    depends_on:
      postgres-test:
        condition: service_healthy
    volumes:
      - ./todo-service:/app
      - /app/node_modules

networks:
  default:
    name: todo-test-network 